name: Create Room Mailboxes

on:
  workflow_dispatch:
    inputs:
      csv_file:
        description: 'CSV file path'
        required: true
        default: 'UsersToMigrate.csv'

jobs:
  create-mailboxes:
    runs-on: windows-latest

    env:
      EXO_APP_ID: ${{ secrets.EXO_APP_ID }}
      EXO_TENANT_ID: ${{ secrets.EXO_TENANT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install ExchangeOnlineManagement
      shell: pwsh
      run: |
        Install-Module -Name ExchangeOnlineManagement -Force -AllowClobber -Scope CurrentUser

    - name: Import Certificate
      shell: pwsh
      run: |
        $pfxBytes = [Convert]::FromBase64String("${{ secrets.EXO_PFX_B64 }}")
        $pfxPath = "$env:TEMP\EXOCert.pfx"
        [IO.File]::WriteAllBytes($pfxPath, $pfxBytes)
        $pwd = ConvertTo-SecureString -String "${{ secrets.EXO_PFX_PASSWORD }}" -AsPlainText -Force
        $cert = Import-PfxCertificate -FilePath $pfxPath -CertStoreLocation Cert:\CurrentUser\My -Password $pwd
        Write-Output "Certificate imported: $($cert.Thumbprint)"
        echo "CERT_THUMBPRINT=$($cert.Thumbprint)" >> $env:GITHUB_ENV

    - name: Run mailbox creation script
      shell: pwsh
      run: |
        Import-Module ExchangeOnlineManagement
        Connect-ExchangeOnline -AppId "$env:EXO_APP_ID" -CertificateThumbprint "$env:CERT_THUMBPRINT" -Organization "$env:EXO_TENANT_ID"

        # Run your script with input
        ./CreateRoomMailbox.ps1 "${{ github.event.inputs.csv_file }}"
