jobs:
  create-mailboxes:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install ExchangeOnlineManagement
      run: Install-Module -Name ExchangeOnlineManagement -Force -AllowClobber -Scope CurrentUser

    - name: Run mailbox creation script
      shell: pwsh
      env:
        EXO_PFX_B64: ${{ secrets.EXO_PFX_B64 }}
        EXO_PFX_PASSWORD: ${{ secrets.EXO_PFX_PASSWORD }}
        EXO_APP_ID: ${{ secrets.EXO_APP_ID }}
        EXO_TENANT_ID: ${{ secrets.EXO_TENANT_ID }}
      run: |
        Import-Module ExchangeOnlineManagement

        # Decode and import PFX certificate
        $pfxBytes = [Convert]::FromBase64String($env:EXO_PFX_B64)
        $pfxPath = "$env:TEMP\EXOCert.pfx"
        [IO.File]::WriteAllBytes($pfxPath, $pfxBytes)
        $pwd = ConvertTo-SecureString -String $env:EXO_PFX_PASSWORD -AsPlainText -Force
        $cert = Import-PfxCertificate -FilePath $pfxPath -CertStoreLocation Cert:\CurrentUser\My -Password $pwd
        Write-Output "Certificate imported: $($cert.Thumbprint)"

        # Connect to Exchange Online using app-based authentication
        Connect-ExchangeOnline -AppId $env:EXO_APP_ID -CertificateThumbprint $cert.Thumbprint -Organization $env:EXO_TENANT_ID

        # Run mailbox creation script
        ./CreateRoomMailbox.ps1 "${{ github.event.inputs.csv_file }}"
